# Generated by Django 2.2.6 on 2019-11-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complain',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='father_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='mother_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
